### ISSUE TITLE
`ocrd workspace add` adds two `mets:FLocat` at once

### ISSUE THREAD

**Issue by csidirop** [OCR-D/core#1135]
I found a regression in the last releases (at least 2.57.2). 

Calling `ocrd --log-level INFO workspace add --force --file-grp FULLTEXT --file-id ... --page-id=... --mimetype text/xml ...` creates two `mets:FLocat`-elements:

```
    <mets:fileGrp USE="FULLTEXT">
      <mets:file ID="..." MIMETYPE="text/xml">
        <mets:FLocat xlink:href="....xml" LOCTYPE="OTHER" OTHERLOCTYPE="FILE"/>
        <mets:FLocat xlink:href="....xml" LOCTYPE="URL"/>
      </mets:file>
    </mets:fileGrp>
```

I have not looked at when this regression occurred, but with ocrd, version 2.52.0 it wasn't there yet.

**Comment by kba** [comment]
It's a feature not a bug :) 

Introduced in https://github.com/OCR-D/core/releases/tag/v2.54.0, we do now separate `mets:FLocat` between what was originally in the `mets.xml` - which should be remote URL in virtually all cases - and what is downloaded by OCR-D/core - which is a file path relative to the `mets.xml`.

In the former case, this `mets:FLocat` will have `@LOCTYPE='URL'`, in the former case `@LOCTYPE='OTHER' @OTHERLOCTYPE='FILE'`.

The reason for that is that we want to make sure, downloads are non-destructive, so that you can remove/rewrite the downloaded files from the `mets.xml` easily and still know which remote URL they manifest locally.

To remove the ``mets:FLocat[@OTHERLOCTYPE='FILE']`, use the `ocrd workspace find --undo-download` command.

**Comment by csidirop** [comment]
Oh thanks :D
