### ISSUE TITLE
xmllint

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#158]
I am trying to set up a working travis ci for [cis-ocrd-py](https://github.com/cisocrgroup/cis-ocrd-py). I keep getting errors that `xmllint` cannot be found (ocrd/utils.py:80). It works locally, since I have installed libxml on my machine. 

I am not sure how to fix this:
* adding lxml to cis-ocrd-py's requirements.txt doesn't seem to work
* installing `lixml2-dev`, `libxslt-devel` as explained [here](https://lxml.de/installation.html) doesn't seem to work either
* using `STATIC_DEPS=true pip install -r requirements.txt` also doesn't seem to work

Has anyone any idea on this?

**Comment by finkf** [comment]
To clear this up, I think that ocrd should handle its requirements, so clients of ocrd do not have to handle the installation of lxml and xmllint

**Comment by kba** [comment]
The python package `lxml` is a hard requirement but there should be pre-built binaries available via pypi for all unix-y platforms. With `libxml2-dev` installed, `STATIC_DEPS` should not be necessary.

`xmllint` should not be required anymore since [`0.7.1`](https://github.com/OCR-D/core/releases/tag/v0.7.1). [Line 80 of utils.py](https://github.com/OCR-D/core/blob/master/ocrd/utils.py#L80) should be an empty line.

**Comment by kba** [comment]
The problem was that `setup.py` referenced `v0.7.0` of core which did indeed still have the dependency on libxml2-utils.
