### ISSUE TITLE
python api: do not use kwargs for required parameters

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#166]
https://github.com/OCR-D/core/blob/ff7e79b9f9e37c4ecf34959629ef096e8f3593c5/ocrd/processor/base.py#L137

`def add_output_file(self, basename=None, file_grp=None, ID=None, **kwargs)`: implies that I can call this function from a processor instance without any arguments. But if I do, an exception is raised.

I'd suggest to set basename to self.basename if basename is none or to require basename as an argument.

From the code I cannot really tell which parameters need to be set.

**Comment by kba** [comment]
I see why this is confusing but in this case it would be best IMHO to remove the helper `add_output_file` from `Processor` rather than change the signatures. It is a thin wrapper around `self.workspace.add_file` for which `basename` is actually optional under certain circumstances (`local_filename` being set), so rather than "simplify" things with redundancy, it seems best to have just one slightly more verbose way to do things and document it in one place.

Would that be okay with you?

Mentioning @bertsky since this might break their tools.

**Comment by finkf** [comment]
I am OK with it. 
I already removed all calls to processor.add_output_file in our tools.
Maybe It would be enough to mark them as deprecated for now.

**Comment by kba** [comment]
> Maybe It would be enough to mark them as deprecated for now.

Good point.

**Comment by kba** [comment]
`Processor.add_output_file` has been removed in 1.0.0b1
