### ISSUE TITLE
For headless systems libsm6 is missing

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/core#234]
Add opencv-python-headless as dependency.

**Comment by stweil** [comment]
@kba, what about tagging a new release with this fix?

`pip install ocrd` still installs `opencv-python`, while `pip install ocrd_tesserocr` installs `opencv-python-headless`.

So we currently depend on both variants of OpenCV. This makes installation on ARM systems very time consuming, because both packages have to be built.

**Comment by kba** [comment]
> @kba, what about tagging making a new release with this fix available for pip?

Proper 1.0.0 release is coming soon. For now `pip install --pre ocrd` or `pip install ocrd==1.0.0b17`.
