### ISSUE TITLE
allow passing param json via stdin in CLI

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#239]
Sometimes it is preferable to specify parameters for processing on the fly. But the CLI module expects a filesystem path. It could be easily extended to allow `-` for stdin as well, by adding `allow_dash=True` to [ocrd_tool_tool_parse_params](https://github.com/OCR-D/core/blob/57e68c578526cb955fd2e368207f5386c459d91d/ocrd/ocrd/cli/ocrd_tool.py#L114), which is available since Click 6.0. This would enable on-the-fly specifications using here strings, e.g.:
```sh
ocrd-tesserocr-recognize -m mets.xml -p - <<<'{ "textequiv_level": "glyph", "model": "Fraktur" }'
```

**Comment by kba** [comment]
As a walkaround in bash/zsh you can also do:

```sh
ocrd-tesserocr-recognize -m mets.xml -p <(echo '{ "textequiv_level": "glyph", "model": "Fraktur" }')
```

which creates an anonymous filehandle or a tempfile on-the-fly.

**Comment by kba** [comment]
Quick ideas on this, since @mikegerber also ran into this:

1) Allow passing STDIN to `-p` as @bertsky suggested
2) Check the string passed to `-p`. If it begins with `{`, treat it as a JSON string, parse it. Otherwise, treat it as a filename, read it and parse it.
3) Additional parameter `-P` which accepts a JSON string and parses it. `-P` string merged on top of `-p` merged on top of default params.

I would prefer not to change anything but if we do, I'd favor option 2 since it's the simplest to implement both by us and workflow composers.

**Comment by bertsky** [comment]
1 does not work in the workflow cli syntax, and 2 could introduce surprise crashes with strange filenames, so I opt for 3, which looks very tidy. But I would be happy with 2 as well.

**Comment by mikegerber** [comment]
I'd prefer 3, too, as it seems to be the most comfortable and least hacky option.

**Comment by kba** [comment]
@wrznr suggested 2) with inverted logic: If the string **is** a valid filename (file is readable), use it as such. Otherwise try to parse as JSON and throw an exception if it does not.

Would that be acceptable?

**Comment by bertsky** [comment]
Fine with me.

**Comment by mikegerber** [comment]
I don't like the heuristics idea that much because it is absolutely possible that a user specifies a wrong filename, but instead of getting some "file not found error", she gets a "JSON parse error". But that's just my opinion, please do as you like :)

**Comment by mikegerber** [comment]
Looks good @kba :)
