### ISSUE TITLE
validate imagines local images as remote

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#248]
`ocrd workspace validate` imagines clearly local images as remote images:

~~~sh
cd `mktemp -d`
wget -q https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/f15fb8c8-3842-4314-9a44-5e8b472d7bfc/data/buerger_gedichte_1778.ocrd.zip
dtrx buerger_gedichte_1778.ocrd.zip
cd buerger_gedichte_1778.ocrd/data
ocrd workspace validate mets.xml
~~~

yields:

~~~xml
<report valid="true">
  <notice>Won't download remote image <OCR-D-IMG/OCR-D-IMG_0001></notice>
  <notice>Won't download remote image <OCR-D-IMG/OCR-D-IMG_0002></notice>
</report>
~~~

**Comment by kba** [comment]
URL handling is a mess. I'll look into it. Thanks for raising. It's one of these whack-a-mole type situations where "fixing" one area causes area in another. Related to the problem of aligning PAGE and METS image filenames and handling absolute file paths and file URL.

**Comment by kba** [comment]
https://github.com/OCR-D/core/pull/303 should fix this but it's hard to test because GT is currently broken. The current version of the GT you reference is at https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/94e7b0ef-fa29-4639-b8e8-36faa7deee87/data/buerger_gedichte_1778.ocrd.zip 

But at least, the validator isn't fooled by relative file names anymore.
