### ISSUE TITLE
Bagit should produce files with extension

### ISSUE THREAD

**Issue by tboenig** [OCR-D/core#258]

**Comment by bertsky** [comment]
I concur. The problem seems to be that [in WorkspaceBagger._bag_mets_files](https://github.com/OCR-D/core/blob/6f925e3803725f05617a200c29e8cf8cb3ba7d85/ocrd/ocrd/workspace_bagger.py#L77) the general `Resolver.download_to_directory` is used (with just the file ID as a basename). IMO, [here](https://github.com/OCR-D/core/blob/6f925e3803725f05617a200c29e8cf8cb3ba7d85/ocrd/ocrd/resolver.py#L57) we should look at the MIME type and add a suffix.
