### ISSUE TITLE
I can not open the PAGE files in Aletheia or Transkribus

### ISSUE THREAD

**Issue by tboenig** [OCR-D/core#331]
Some things are problematic:
1. The PAGE XML cannot be validated because there is no link to a schema/DTD. Specifying a namespace is not such a linking to schema.
2. Because no other namespace is used, it makes no sense to specify the namespace in which the elements are marked with the namespace. (e.g. pc:Page).
3. In this form the file can be displayed in the PageViewer, it can be transformed with X-technologies, that's fine, but it cannot simply be edited with tools like Alethei or Transkribus. The files must be converted at first. This is very impractical.

**Comment by bertsky** [comment]
>     1. The PAGE XML cannot be validated because there is no link to a schema/DTD. Specifying a namespace is not such a linking to schema.

You mean the `@xsi:schemaLocation` on the root element? I think it would be easy to change `ocrd_models.ocrd_page.to_xml()` to specify that as well. @kba?

>     2\. Because no other namespace is used, it makes no sense to specify the namespace in which the elements are marked with the namespace. (e.g. pc:Page).

It's true we cannot use other namespaces in PAGE-XML documents, and therefore have no actual need for a namespace prefix. Nevertheless, this is perfectly valid (PAGE) XML. Are you saying Aletheia and Transkribus cannot cope with the prefix, or it is merely too verbose for you to read personally?

>     3\. In this form the file can be displayed in the PageViewer, it can be transformed with X-technologies, that's fine, but it cannot simply be edited with tools like Alethei or Transkribus. The files must be converted at first. This is very impractical.

We should definitely make this work. But since you made this point number 3, are you implying that there is yet another (third) reason for Aletheia and Transkribus to refuse opening the files directly? (Or was this simply a summary of 1 and 2?)

**Comment by tboenig** [comment]
Thanks bertsky,

``this is perfectly valid (PAGE) XML.`` On the general site you have right. But strictly according to the XML recommendation it is not. The PAGE files are only well-formed files. (see: https://www.w3.org/TR/xml/#dt-valid and https://www.w3.org/TR/xml/#dt-wellformed).

Tools like Aletheia or Transkribus are only examples of the effects this approach has. I don't think these tool providers should change anything. If we say that the PAGE file is perfect, then we should also link the file to the schema.

Yes, another reason is that if you are developing a tool for OCR-D page files, you will also need an interpreter for the well-formed page files. If you have valid page files, you can be sure that's PAGE. You can use an normal validation parser. The development of specific features or functions can use this validation and do'nt need a specific interpreter for the wellformed PAGE files.

**Comment by kba** [comment]
> Because no other namespace is used, it makes no sense to specify the namespace in which the elements are marked with the namespace. (e.g. pc:Page).

That's just a convention, all XML libraries should be able to handle this.

> 1. The PAGE XML cannot be validated because there is no link to a schema/DTD. Specifying a namespace is not such a linking to schema.

I'll add that.
