### ISSUE TITLE
ocrd process: Parameters should be passable as JSON string 

### ISSUE THREAD

**Issue by kba** [OCR-D/core#345]

**Comment by bertsky** [comment]
...or perhaps easier for the implementation (when parsing and expanding shell syntax) and for callers (like makefiles) alike: allow passing parameters in common CLI configuration conventions, e.g. `-p oplevel=page -p overwrite_words=true`.

**Comment by bertsky** [comment]
(But maybe that's worth another option name, like `-P`, and should first go through the spec.)

**Comment by kba** [comment]
Since 2805da94 this is implemented, i.e. you can do

```sh
ocrd process "foo-processor -I FOO -O BAR -p "{\"foo\": \"bar\"}"'
```

which arguably isn't pretty but easier than with shell/file interpolation.

> allow passing parameters in common CLI configuration conventions, e.g. `-p oplevel=page -p overwrite_words=true`.

That would make the parsing much harder. "JSON object serialization or filename" is somewhat complex but "JSON object serialization or filename or equal-sign-separated key-value pairs" is really complex.

How about a simple syntax like hJSON or some YAML dialect that allows inline key-value-pairs without the pain of quoting everything? Then we could use a library for that.

**Comment by bertsky** [comment]
> Since [2805da9](https://github.com/OCR-D/core/commit/2805da9418c9570edd2fa95513f23949786026e5) this is implemented

Indeed! I had not taken notice, yet. Thanks!

> That would make the parsing much harder. "JSON object serialization or filename" is somewhat complex but "JSON object serialization or filename or equal-sign-separated key-value pairs" is really complex.

That's why I proposed to offer that under a separate option name, `-P` (capital-p). (And there are libraries for that, too.)

> How about a simple syntax like hJSON or some YAML dialect that allows inline key-value-pairs without the pain of quoting everything? Then we could use a library for that.

Quoting is a problem for `ocrd process`, commas are for `make` (which treats both quotes and commas as normal characters and has no escapement mechanism besides its own variable expansion scheme). Another syntax could probably solve this as well, yes. But then again we go against principle of least astonishment:
- This is a CLI. It uses POSIX conventions. One would expect the same to hold for the parameter settings.
- We already require JSON for the tool description, and have documented JSON for runtime parameters everywhere.

So hJSON et al would violate both expectations, while pure JSON (as already available now) or getopts syntax would only violate either one.

**Comment by bertsky** [comment]
The original request is supported since #307. Shall we make this about supporting an additional syntax in POSIX fashion (via `-p`), or close?

**Comment by EEngl52** [comment]
@kba can this be closed?

**Comment by bertsky** [comment]
Yes, it works on all CLIs now. If the need (and consensus) for an additional syntax should arise, we can always re-open.
