### ISSUE TITLE
Possible regression of "ocrd workspace add" in 2.10.2

### ISSUE THREAD

**Issue by kba** [OCR-D/core#519]
@M3ssman in https://gitter.im/OCR-D/Lobby?at=5ee8b1e77c64f31f1163ea9b :

> I just met some ... different behavior. When I add a local file to a fresh workspace with ocrd V2.10.2, the Image file itself is not copied anymore to the directory with the according fGroup-Label, like it did just 2 weeks before ... even the brand new existance-check has nothing to complain about (but it complains quite fine if the file doesn't exist). So if I type `ocrd workspace add -m image/jpg -G MAX -i IMG_MAX_1818975 -C /home/hartwig/Projekte/work/mlu/ulb/ulb-it-vd-ocr/data/IMG_MAX_1818975.jpg` only the mets-file is updated and nothing else. Did I miss something?

**Comment by bertsky** [comment]
@kba I believe the problem is here:
https://github.com/OCR-D/core/blob/86f788aed67f1ad0e7cf61141baa818f6e8dd504/ocrd/ocrd/cli/workspace.py#L158

The `ctx.directory` is converted into an absolute pathname in the context object's constructor. Thus, if you call with an absolute path name into the workspace, nothing happens

**Comment by kba** [comment]
@M3ssman Is `/home/hartwig/Projekte/work/mlu/ulb/ulb-it-vd-ocr/data/` the workspace directory? And you want the file to be copied to `home/hartwig/Projekte/work/mlu/ulb/ulb-it-vd-ocr/data/MAX /IMG_MAX_1818975.jpg`? This does not work with the current implemntation because that file is already in the workspace, though not at the location you expect.

We could change the behavior to make the check not only if the file is in the workspace but also if it is at the location that the parameters imply. Hoever in that case, you would end up with copies of the files.

Would it not be easier to either put the files in the right subfolder in the first place or to copy the files from outside the workspace?

**Comment by M3ssman** [comment]
No, the files are completely outside. 
`ulb-it-vd-ocr/data/` is just a folder with image data. The actual OCR-D-workspaces are located in `ulb-it-vd-ocr/TMP`, like `ulb-it-vd-ocr/TMP/1000`, `ulb-it-vd-ocr/TMP/1001`.. and so on.

For my workflows this is a rather breaking change since classically they were copied from any absolute local path into the workspace group folder. But if I know how to handle, it's fine as it is. 
There were some discussions about Release Management :smirk: 
Don't worry, everything will be alright :sunglasses: Feel free to close

**Comment by kba** [comment]
No, in that case it really is a regression, I will try to replicate.
