### ISSUE TITLE
[Model Documentation] Fraktur call is not correct

### ISSUE THREAD

**Issue by GrazingScientist** [OCR-D/core#567]
**Used Docker image**
`docker.io/ocrd/all   maximum   7bfeac60c4cb   5 days ago     12.4 GB`

**Problem Description**
Using the OCRD Docker image, the call to the tesseract `Fraktur` model given in the documentation [here](https://ocr-d.de/en/models#tesseract--ocrd_tesserocr) fails.

When I install the `Fraktur` model via `apt install tesseract-ocr-script-frak`, the call to `ocrd-tesserocr-recognize -I OCR-D-SEG-LINE -O OCR-D-OCR-TESS_DEU_FRAK -p '{"model": "deu+frk"}'` as given in the documentation fails.

The correct call would be:

```
ocrd-tesserocr-recognize -I OCR-D-SEG-LINE -O OCR-D-OCR-TESS_DEU_FRAK -p '{"model": "deu+Fraktur"}'
```

Also, by the way, I had to set `TESSDATA_PREFIX` in the Dockerfile as
```
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
```
because otherwise the models are not found. Can you reproduce this?

**Comment by bertsky** [comment]
I am afraid your case – ocrd_all via Docker image – is not covered by ocrd.de documentation yet. So that's actually a documentation issue (should be moved to ocrd-website). Or you could say it's an ocrd_all issue, but not core.

The situation in the Docker image is different, because Tesseract has been installed from source there (not apt), so models reside in a custom path (`/usr/local/share/tessdata`), but you cannot use the ocrd_all make rules to fetch additional models.

> Also, by the way, I had to set `TESSDATA_PREFIX` in the Dockerfile as
> 
> ```
> ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
> ```
> 
> because otherwise the models are not found

This makes your ocrd_tesserocr use _only_ models you can install via apt. The default path for the Docker version is `/usr/local/share/tessdata` (with only the minimal `osd`/`eng`/`equ` installed). It's not exported to the shell, though.

I agree we should find a better solution (either use the apt default path, or at least export `TESSDATA_PREFIX` correctly).

Also, note that frk and Fraktur are actually different kinds of fraktur models:
* [frk](https://github.com/tesseract-ocr/tessdata_fast/raw/master/frk.traineddata) / `tesseract-ocr-frk`: unlike the apt description, this is not Frankish, but a modern (LSTM-based) Fraktur model for German
* [Fraktur](https://github.com/tesseract-ocr/tessdata_fast/raw/master/script/Fraktur.traineddata) / `tesseract-ocr-script-frak`: pure (without LM/dict) LSTM-based Fraktur model for all languages

You can even combine them: `frk+Fraktur`.
