### ISSUE TITLE
Deprecation of Python 3.6

### ISSUE THREAD

**Issue by kba** [OCR-D/core#697]
Python 3.6 will reach end-of-life at the end of 2021 and more and more libraries and tools that we rely on in OCR-D stop supporting Python 3.6 in favor of Python 3.7+. Currently, Ubuntu 18 with Python 3.6 is our target platform, but we want to move to Python 3.7 as soon as possible.

AFAICT today, most OCR-D users have moved on to Python 3.7. So we will drop support for Python 3.6 on **September 30, 2021**.

If you are using OCR-D with Python 3.6 and cannot easily upgrade, please get in touch by answering on this issue or in [our gitter chat](https://gitter.im/OCR-D/Lobby).

**Comment by bertsky** [comment]
For the grace period, I suggest building Python 3.7 images in addition to the current Python 3.6 based images for exhaustive testing in parallel to normal updates.

Changes:
- Makefile: change `deps-ubuntu` to be responsive to `PYTHON` envvar (so that `make deps-ubuntu PYTHON=python3.7` will `apt-get install python3.8 python3-pip python3-venv`)
- .circleci/config.yml: additional build config `deploy37` which runs make with a `PYTHON=python3.7 DOCKER_TAG=ocrd/core3.7` (and `DOCKER_TAG=ocrd/core3.7-cuda`) override and thus produces `ocrd/core37` (and `ocrd/core37-cuda`)
- in ocrd_all: additional config which this as `DOCKER_BASE_IMAGE` and builds `ocrd/all37:{mini,medi,max}mum{,-cuda{,-git}}`

(One could also move the Python version tag from the image name into the image version, i.e. `ocrd/core:3.7` / `ocrd/all:3.7`, but I think this is not the best choice.)
