### ISSUE TITLE
workspace list-page: show label

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#821]
Sometimes physical page identifiers look like `phys_fcd565cd-d170-4774-bb37-9aa25b68370b` – which is impossible to type/memorize. But even names like `PHYS_0001` are not as helpful as the `@ORDERLABEL` and `@ORDER` attributes.

Since presentation systems usually combine the latter two (`@ORDER [@ORDERLABEL]` IINM) we should offer something of the sort, too.

So `ocrd workspace list-page` could use an option (for backwards compatibility) to display these labels in extra columns.

But also, the page range operator could be made aware (somehow) of these labels, allowing me to specify, say `-g 20` instead of `-g phys_fcd565cd-d170-4774-bb37-9aa25b68370b`.

**Comment by bertsky** [comment]
> We would have to refactor `OcrdMets.physical_pages` to return the complete `mets:div` element (instead of just the `@ID` string), so all attributes can be queried from it.

Oh, I completely forgot about #1063, which already solves that first part (by providing an extra kwarg to `get_physical_pages`).

**Comment by kba** [comment]
All of these features are now merged with #1063:

* `OcrdMets.get_physical_pages` can return the `mets:div` elements instead of just the `ID`
* `ocrd workspace list-page` supports `ORDER`, `ORDERLABEL`, `LABEL` and `CONTENTIDS` in addition to `ID`
* `ocrd workspace update-page --set` allows setting them
* `-g` ranges can refer to any of them
